# Jekyll configuration for GitHub Pages
exclude:
  - build/
  - .gitignore
  - README.md
  - "*.md"
  
# GitHub Pages settings
plugins:
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings