# Netlify configuration for Emoty Beta Signup
[build]
  # Build command (if needed for static site generation)
  command = "echo 'Static site - no build needed'"
  publish = "."
  
  # Environment variables for build (if needed)
  [build.environment]
    NODE_VERSION = "18"

# Function settings
[functions]
  # Directory containing Netlify Functions
  directory = "netlify/functions"
  
  # Runtime settings
  node_bundler = "esbuild"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Headers for API endpoints
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://emoty.fr"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

# Redirects for API endpoints (optional - for cleaner URLs)
[[redirects]]
  from = "/api/beta-signup"
  to = "/.netlify/functions/beta-signup"
  status = 200

[[redirects]]
  from = "/api/resend-confirmation"
  to = "/.netlify/functions/resend-confirmation"
  status = 200

[[redirects]]
  from = "/api/confirm-signup"
  to = "/.netlify/functions/confirm-signup"
  status = 200

# Form handling (alternative simple approach)
# Uncomment if you want to use Netlify Forms instead of functions
# [[redirects]]
#   from = "/beta-signup-simple"
#   to = "/beta-signup-thanks"
#   status = 200
#   conditions = {Role = ["admin"]}

# Edge functions (if needed for advanced features)
# [[edge_functions]]
#   function = "rate-limiter"
#   path = "/api/*"

# Plugin configuration
# [[plugins]]
#   package = "@netlify/plugin-sitemap"

# Environment variable validation (optional)
# [context.production.environment]
#   AIRTABLE_API_KEY = "required"
#   AIRTABLE_BASE_ID = "required"
#   MAILGUN_API_KEY = "required"
#   MAILGUN_DOMAIN = "required"