name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: List repository contents
      run: |
        set -e
        echo "=== Repository contents ==="
        ls -la
        echo "=== Checking for key files ==="
        test -f index.html && echo "✓ index.html exists" || echo "✗ index.html missing"
        test -f .nojekyll && echo "✓ .nojekyll exists" || echo "✗ .nojekyll missing"
        test -f CNAME && echo "✓ CNAME exists" || echo "✗ CNAME missing"
        test -d en-GB && echo "✓ en-GB/ exists" || echo "✗ en-GB/ missing"
    
    - name: Prepare site for deployment
      run: |
        set -e
        echo "=== Creating deployment directory ==="
        mkdir -p _deploy
        
        echo "=== Copying site files ==="
        cp index.html _deploy/
        cp -r eli5/ _deploy/
        cp -r en-GB/ _deploy/
        cp -r tu/ _deploy/
        cp -r privacy-policy/ _deploy/
        
        # Copy special files if they exist
        [ -f .nojekyll ] && cp .nojekyll _deploy/
        [ -f CNAME ] && cp CNAME _deploy/
        
        echo "=== Deployment directory contents ==="
        ls -la _deploy/
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: _deploy
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4